export ZSH=/Users/max/.oh-my-zsh

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh
export TERM="screen-256color"

export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="$PATH:$(which elixir)"
export PATH="$PATH:$(which elixirc)"
export PATH="$PATH:$(which iex)"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/usr/local/go/bin"

source ~/Documents/dotfiles/Configuration/secret

export LANG=en_US.utf8

source ~/.antigenrc

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Override normal cd to use lf (github.com/gokcehan/lf)
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

#Aliases and command mods
cd() { builtin cd "$@" && ls; }
..() { builtin cd .. && ls; }
# cd() { lfcd }
alias reload="exec zsh"
alias l="ls -a"
alias g="git"
alias ga="git add -A"
alias gcm="git commit -m "
alias gp="git push"
alias gl="git pull"
alias gs="git status"
alias glog="g log --oneline --graph --stat --decorate"
alias oc="sudo openconnect"
alias j="autojump"
alias gf="git-flow"
alias m="mix"
alias mr="mix run"
alias iexs="iex -S mix"
alias iexsr="iex -S mix run"
alias nv="nvim"
alias ta="tmux a -t"
alias tns="tmux new -s"
alias tcs="tns"
alias tls="tmux ls"
alias tks="tmux kill-session -t"
alias vi="nvim"
alias vim="nvim"
alias VIM="sudo nvim"
alias .="nvim ."
alias cat="bat --theme=GitHub"

clear
